version: '3.9'

services:
  webapp:
    build: .
    volumes:
      - .:/app
    ports:
      - 9090:9090
    environment:
      - SEARCH_QUERY='cricket' # Hardcoded search query
      - QUERY_PER_PAGE=20
    command: >
      bash -c "python manage.py migrate
      && python manage.py collectstatic --noinput
      && uvicorn fampay.asgi:application --reload --host 0.0.0.0 --port 9090"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    ports:
      - 5430:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./config/local.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fampay"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgbouncer:
    image: brainsam/pgbouncer
    env_file:
      - ./config/local.env

  redis:
    image: redis:latest
    ports:
      - 6370:6379

volumes:
  postgres_data:
